#!/bin/bash
read -r min1 min5 min15 _ < /proc/loadavg
echo "-----------------------"
echo "CPU `LC_ALL=C top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\
\1/" | awk '{print 100 - $1 "%"}'`"
printf "MEMORY: $(free -m -h | awk '/Mem/{print $3"/"$2}')"
echo
printf "LOADAVG: %s\n" "$min1 $min5 $min15"
echo "-----------------------"
echo
sensors | grep -A 3 k10
echo
ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 4
echo
echo
tlp-stat -b | rg power_now
echo
echo
genlop -ci
